export const hexColors = {
  light: {
    black: "#000000",
    white: "#FFFFFF",
    header: "#1351B4",
    background: "#FFFFFF",
    foreground: "#2A2A2A",
    primary: "#1351B4",
    primaryLight: "#E1E7F1",
    secondary: "#3A4A6A",
    secondaryLight: "#DCE4F5",
    typography: "#2A2A2A",
    typographyForeground: "#F5F5F5",
    muted: "#BDBDC0",
    grayDarker: "#3C3C43",
    accentForeground: "#FB7D41",
    destructive: "#FECACA",
    highlightDarkbrown: "#5A0C0C",
    highlightBrown: "#D8110B",
    success: "#D1FAE5",
    highlightDarksuccess: "#0D4220",
    highlightSuccess: "#166534",
    warning: "#FEF3C7",
    highlightDarkwarning: "#7C3A06",
    highlightWarning: "#B45309",
  },
  dark: {
    black: "#000000",
    white: "#FFFFFF",
    header: "#0D1B2A",
    background: "#1B263B",
    foreground: "#E9ECF2",
    primary: "#1351B4",
    primaryLight: "#E1E7F1",
    secondary: "#3A4A6A",
    secondaryLight: "#DCE4F5",
    typography: "#FFFFFF",
    typographyForeground: "#F5F5F5",
    muted: "#BDBDC0",
    grayDarker: "#3C3C43",
    accentForeground: "#FB7D41",
    destructive: "#FECACA",
    highlightDarkbrown: "#5A0C0C",
    highlightBrown: "#D8110B",
    success: "#D1FAE5",
    highlightDarksuccess: "#0D4220",
    highlightSuccess: "#166534",
    warning: "#FEF3C7",
    highlightDarkwarning: "#7C3A06",
    highlightWarning: "#B45309",
  },
} as const;

export type ColorTheme = keyof typeof hexColors;
export type ColorKey = keyof (typeof hexColors)["light"];
export type HexColor = (typeof hexColors)[ColorTheme][ColorKey];
export type IHexColors = Record<ColorKey, HexColor>;
